export const CITIES = [
  'Thành phố Hồ Chí Minh',
  'Hầ Nội',
  'Đà Nẵng',
  'Quảng Nam',
  'Quảng Ngãi',
  'Quảng Bình',
  'Đà Lạt',
  'Cần Thơ',
  'Huế',
  'Đồng Tháp',
  'Gia Lai',
  'Quảng Trị',
  'Đồng Nai',
  'Tiền Giang',
  'Kiên Giang',
  'Khánh Hòa',
  'Thanh Hóa',
  'Thái Bình',
  'Quảng Ninh',
  'Hải Phòng',
  'Bến Tre',
  'Bắc Giang',
  'Bình Dương',
  'Bình Định',
];
